
      // This file is generated by npm run icons:build
      export type IconName =
      	| "circle-user-round"
	| "circle-user"
	| "computer"
	| "fly"
	| "inertia"
	| "laptop"
	| "laravel"
	| "log-out"
	| "mantine"
	| "phone"
	| "resend"
	| "settings"
	| "user-round"
	| "user"
	| "vitejs"
    